# Forward

In this forward I want to preach the principal of the 20/80 rule: that 80% of the gain you can get out of programming comes from the first 20% of work. 

You don't have to have a degree in computer science to use python to analyze data. Just like cooking there is quite a lot you can do from the comfort of your own home with just a little bit of practice and a recipe.

In that vein, the goal of this notebook is to provide some 'recipes' for analyzing the 17lands data so you can try to whip up some answers of to your own draft related questions.

This notebook starts out very basic and ramps up to some more complex recipes, but I attempted to select the examples such that they cover a wide variety of types of things you might want to do. Feel free to skip around if you already know what you are doing.
|
Before you start, if you have never programmed before, I would recommend being familiar with the python basics. Specifically:

* Variables
* If-Then Logic
* For loops
* Functions

All of this is very learnable in a weekend or two and there are plenty of resources which are available online to get you started

# Basics #0: Setup

Installing python is very platform dependent. If you have never worked with a coding language before it can be very daunting, but the jist of it is you want to google how to install python for your operating system. Then you want to install `pip`, the python package manager. Once you setup `pip`, install something called `pandas`. 

This may take a bit of googling, but don't get discouraged! It's very normal to get stuck. You would be surprised though how often the right solution is in the top 10 google results.

If you get stuck for more than 30 minutes on any particular step (and this goes for any point in the tutorial) then I recommend reaching out for help. They are very helpful in the 17lands discord. You would also be surprised how many people know a bit of coding in the general magic community and can probably help you out with the basics of getting set up.

If you like the look and feel of this guide, it is written using a jupyter notebook which is also awesome for Data Science if you want to give it a go.

# Basics #1: Importing a CSV File

17lands gives us their data in what is called a CSV format. If you were to open it up in a text editor, it might look like this:

```
index,name
0,pilfering hawk
1,battle mammoth
2,"jorn, god of winter // kaldring, the rimestaff"
3,rune of might
4,reflections of littjara
5,esika's chariot
6,binding the old gods
```

CSV stands for Comma Separated Values and as you can see, it's just a way to store a table of data using commas to separate the fields. If you were to show the data in a table it would look like this

| index | name|
|--|----|
|0|pilfering hawk|
|1|battle mammoth|
|2|"jorn, god of winter // kaldring, the rimestaff"|
|3|rune of might|
|4|reflections of littjara|
|5|esika's chariot|
|6|binding the old gods|

This is how the 17lands data is represented in a big text file. Pandas gives a real convenient interface for importing a csv. The above data is a selection from a csv of blue and green cards from Kaldheim. To open the csv in pandas, you would use the following snippit of code which you can see when run (the input code has an output) outputs the same table, but with more data.

In [1]:
# Importing the pandas package lets you call library functions from pandas
# We import as pd, since we are going to be using it a lot. This is considered pretty standard
import pandas as pd

# This is a pandas library function to open up a csv file
# Notice that the table is simil
pd.read_csv("khm_ug.csv")

     index                                            name
0        0                                  pilfering hawk
1        1                                  battle mammoth
2        2  jorn, god of winter // kaldring, the rimestaff
3        3                                   rune of might
4        4                         reflections of littjara
..     ...                                             ...
99      99                           king harald's revenge
100    100                                      tyvar kell
101    101                                depart the realm
102    102                              strategic planning
103    103                               ravenous lindwurm

[104 rows x 2 columns]

# Basics #2: Reading the data frame

Now that you have a handle on the csv format, lets actually look at the data. For this analysis I'm using a data dump from the Crimson Vow draft data. You can download the latest draft data here:https://www.17lands.com/public_datasets

I would recommend starting with the game data which gives data on how each game went, where as the draft data gives information on each pick

Using the same `read_csv()` function above, you can open the data. The result that you get out is called a pandas Data Frame(df). The data frame has the key attributes: column names and rows. I will show below how to access a data frame using the columns and rows.

In [2]:
import pandas as pd

# We added the chunksize argument because the data is so large. Chunk size only takes the first `N` values out of the file
# into what's called an iterator. To access the next item in an iterator, you use the `next()` function on it.
# 100000 rows is enough to do some preliminary reading
# If you use a Jupyter notebook you want to do this in it's own cell because the notebook will keep the data loaded
# even when you rerun other cells
df = next(pd.read_csv("game_data_public.VOW.PremierDraft.csv", chunksize=100000))

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [3]:
# The Header is like names of all the fields you may want to work with
df.columns

Index(['user_win_rate_bucket', 'user_n_games_bucket', 'draft_id',
       'build_index', 'draft_time', 'expansion', 'event_type', 'game_number',
       'rank', 'opp_rank',
       ...
       'sideboard_Wedding Invitation', 'sideboard_Wedding Security',
       'sideboard_Welcoming Vampire', 'sideboard_Whispering Wizard',
       'sideboard_Winged Portent', 'sideboard_Witch's Web',
       'sideboard_Witness the Future', 'sideboard_Wolf Strike',
       'sideboard_Wolfkin Outcast', 'sideboard_Wretched Throng'],
      dtype='object', length=1106)

In [4]:
# Select a couple of the columns, as you probably don't care about all of them
# Notice that each draft will have a seperate row for each match in this data set
df[["draft_id", "user_win_rate_bucket", "game_number", "sideboard_Wretched Throng"]]

,draft_id,user_win_rate_bucket,game_number,sideboard_Wretched Throng
0,5d8cdae6df1441e89e606420770a16c1,0.66,1,1
1,5d8cdae6df1441e89e606420770a16c1,0.66,1,1
2,5d8cdae6df1441e89e606420770a16c1,0.66,1,1
3,5d8cdae6df1441e89e606420770a16c1,0.66,1,1
4,2f742c47d16741cf97b5a520f9650211,0.66,1,0
...,...,...,...,...
99995,0d26516e8a2643dcb7d7b30d16d9f4a2,0.52,1,0
99996,0d26516e8a2643dcb7d7b30d16d9f4a2,0.52,1,0
99997,0d26516e8a2643dcb7d7b30d16d9f4a2,0.52,1,0
99998,8bf7d4cfd23c4864bf3f7653c0840521,0.52,1,1
99999,8bf7d4cfd23c4864bf3f7653c0840521,0.52,1,1

In [5]:
# Grab the first 4 rows for the game data on the first deck in the data set
print(df.iloc[0:4])

   user_win_rate_bucket  user_n_games_bucket  \
0                  0.66                   50
1                  0.66                   50
2                  0.66                   50
3                  0.66                   50

                           draft_id  build_index           draft_time  \
0  5d8cdae6df1441e89e606420770a16c1            0  2021-12-08 21:22:04
1  5d8cdae6df1441e89e606420770a16c1            0  2021-12-08 21:22:04
2  5d8cdae6df1441e89e606420770a16c1            0  2021-12-08 21:22:04
3  5d8cdae6df1441e89e606420770a16c1            0  2021-12-08 21:22:04

  expansion    event_type  game_number                   rank opp_rank  ...  \
0       VOW  PremierDraft            1     Gold-2-None-None-2      NaN  ...
1       VOW  PremierDraft            1     Gold-2-None-None-1      NaN  ...
2       VOW  PremierDraft            1  Gold-2-None-None-None      NaN  ...
3       VOW  PremierDraft            1     Gold-2-None-None-2      NaN  ...

  sideboard_Wedding Invitation sideboard_Wedding Security  \
0                            0                          0
1                            0                          0
2                            0                          0
3                            0                          0

   sideboard_Welcoming Vampire  sideboard_Whispering Wizard  \
0                            0                            0
1                            0                            0
2                            0                            0
3                            0                            0

   sideboard_Winged Portent sideboard_Witch's Web  \
0                         0                     0
1                         0                     0
2                         0                     0
3                         0                     0

   sideboard_Witness the Future  sideboard_Wolf Strike  \
0                             0                      0
1                             0                      0
2                             0                      0
3                             0                      0

   sideboard_Wolfkin Outcast  sideboard_Wretched Throng
0                          0                          1
1                          0                          1
2                          0                          1
3                          0                          1

[4 rows x 1106 columns]

In [6]:
# Read a specific index, in this case: draft id
df.iloc[0,2]

'5d8cdae6df1441e89e606420770a16c1'

# Recipe #1: (Looping over data) What is the average winrate of 17lands users?

In [7]:
# See Basics For reading a data frame to get df
wins = 0
games = 0

# To loop over a pandas frame is really easy with the iterrows function
for index, match in df.iterrows():
    # Select the won field of the match row
    if match["won"] == True:
        wins += 1
    games += 1
    
win_percent = wins/games

from math import sqrt
# For binomially distributed data, the standard deviation is approximated by the formula below.
standard_deviation = sqrt(win_percent * (1 - win_percent) / games)

# Format strings are cool and easy to learn if you want to get into them
print(f"Average winrate {win_percent*100}% +/-{standard_deviation * 100}%")

Average winrate 55.025999999999996% +/-0.15731304218023376%

As you can see the winrate is slightly higher than the expected winrate of 50%. 

A popular theory for why 17lands users have a higher winrate is because in order to be aware of the 17lands client, you are assumed to be on average more exposed to the game than the average person who doesn't and have a higher skill level because you consume a lot of magic content.

The recipe results hits at a really core question that I think anyone who is opening the data wants to know: what causes winrate to go up and down? 

Additionally there is a question: Is this sample is representative of the 17lands population, or is it just a lucky batch of games?

What does this mean if you find a card with a winrate of 50%?

# Recipe #2: (Conditional Selection) Winrate of decks with a specific card

In [8]:
# See Basics For reading a data frame to get df

# filter out the decks with a specific card, in this case: wretched throng copies greater than 0
# We are using loc to filter. Loc selects all rows for which the given statement is true
wretched_throng_decks = df[df['deck_Wretched Throng'] > 0]

throng_wins = 0
throng_games = 0

# Notice we use the wretched throng decks here
for index, match in wretched_throng_decks.iterrows():
    # Select the won field of the match row
    if match["won"] == True:
        throng_wins += 1
    throng_games += 1

throng_win_percent = throng_wins/throng_games

from math import sqrt
# For binomially distributed data, the standard deviation is approximated by the formula below.
throng_standard_deviation = sqrt(throng_win_percent * (1 - throng_win_percent) / throng_games)

# Format strings are cool and easy to learn if you want to get into them
print(f"Average winrate {throng_win_percent*100}% +/-{throng_standard_deviation * 100}%")

Average winrate 53.747934505032305% +/-0.6110928145236563%

Interesting, maybe this changes when you have more throngs?

# Recipe #3: (Add a Column, Groupby) Winrate by number of copies in deck

In [9]:
# Here, instead of tracking the number of wins with a variable, we will do it in the data frame
# First lets get the columns we care about
throng_copy_winrate = df[['won','deck_Wretched Throng']]

# Now, lets add a column for each game, this will seem redundant right now since we know each row is only one game
# Setting the row equal to one initializes each value in the column to 1 game per row.
# It might throw an error, but it will do the job
throng_copy_winrate['num_games'] = 1

# The group by function is a very powerful tool that lets you take a data frame and group it by a column
# You can use several different methods for combining rows, but I usually like summing
# If you did average you could get the same anwer without the num_games column, but then it's hard to see for the smaller
# sample sizes what your error rate is
throng_copy_winrate = throng_copy_winrate.groupby(['deck_Wretched Throng']).sum()

# Now lets add a column for winrate
# If you set and select columns like this in pandas, it's the same as looping over the values
# Remeber to be careful on division as dividing by 0 gives Nan. In this case, the row will always be at least 1
throng_copy_winrate['win_rate'] = throng_copy_winrate['won'] / throng_copy_winrate['num_games']

# You have to use numpy to perform square root on a np.array like object which pandas arrays are
from numpy import sqrt
# Column for estimated error
# Be careful about one liners in python though, since it can be elegant to code, but hard to read
throng_copy_winrate['est_error'] = throng_copy_winrate['win_rate'] * (1 - throng_copy_winrate['win_rate']) / throng_copy_winrate['num_games']
throng_copy_winrate['est_error'] = sqrt(throng_copy_winrate['est_error'])

throng_copy_winrate

<ipython-input-9-dddd3c36f58a>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  throng_copy_winrate['num_games'] = 1

                        won  num_games  win_rate  est_error
deck_Wretched Throng
0                     51448      93343  0.551171   0.001628
1                       415        789  0.525982   0.017776
2                      1573       3006  0.523287   0.009110
3                      1173       2087  0.562051   0.010860
4                       347        648  0.535494   0.019592
5                        55        100  0.550000   0.049749
6                        15         27  0.555556   0.095629

Take note, that there is probably not enough data for the winrates of the 4+ copies of throngs to be conclusive given the estimated error

In [4]:
# Importing the pandas package lets you call library functions from pandas
# We import as pd, since we are going to be using it a lot. This is considered pretty standard
import pandas as pd

iter_csv = pd.read_csv("game_data_public.VOW.PremierDraft.csv", iterator=True, chunksize=1000)
throng_copy_winrate = pd.concat([chunk[['won','deck_Ancestral Anger']] for chunk in iter_csv])

# Now, lets add a column for each game, this will seem redundant right now since we know each row is only one game
# Setting the row equal to one initializes each value in the column to 1 game per row.
# It might throw an error, but it will do the job
throng_copy_winrate['num_games'] = 1

# The group by function is a very powerful tool that lets you take a data frame and group it by a column
# You can use several different methods for combining rows, but I usually like summing
# If you did average you could get the same anwer without the num_games column, but then it's hard to see for the smaller
# sample sizes what your error rate is
throng_copy_winrate = throng_copy_winrate.groupby(['deck_Ancestral Anger']).sum()

# Now lets add a column for winrate
# If you set and select columns like this in pandas, it's the same as looping over the values
# Remeber to be careful on division as dividing by 0 gives Nan. In this case, the row will always be at least 1
throng_copy_winrate['win_rate'] = throng_copy_winrate['won'] / throng_copy_winrate['num_games']

# You have to use numpy to perform square root on a np.array like object which pandas arrays are
from numpy import sqrt
# Column for estimated error
# Be careful about one liners in python though, since it can be elegant to code, but hard to read
throng_copy_winrate['est_error'] = throng_copy_winrate['win_rate'] * (1 - throng_copy_winrate['win_rate']) / throng_copy_winrate['num_games']
throng_copy_winrate['est_error'] = sqrt(throng_copy_winrate['est_error'])

throng_copy_winrate

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

                         won  num_games  win_rate  est_error
deck_Ancestral Anger
0                     258182     472375  0.546562   0.000724
1                       3259       6064  0.537434   0.006403
2                       3742       6870  0.544687   0.006008
3                       3034       5407  0.561124   0.006749
4                       1392       2448  0.568627   0.010010
5                        350        615  0.569106   0.019968
6                        139        214  0.649533   0.032615
7                         21         31  0.677419   0.083959
8                          3          6  0.500000   0.204124